<a href="https://colab.research.google.com/github/choisooyeon007/hello-world/blob/master/Jan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive

In [18]:
!ls /gdrive/My\ Drive/Colab\ Notebooks

change01.csv  change01.xlsx  Untitled0.ipynb

In [0]:
import pandas as pd

In [26]:
Jan = pd.read_csv('/gdrive/My Drive/Colab Notebooks/change01.csv', encoding='euc-kr')
Jan

         기준일ID  시간대구분     행정동코드  ...  여자60세부터64세생활인구수  여자65세부터69세생활인구수  여자70세이상생활인구수
0          101      0  11110515  ...        -0.243243        -0.120000     -0.234043
1          101      0  11110515  ...         1.500000         0.542857      0.692857
2          101      0  11110515  ...        -0.454545        -0.553191     -0.648276
3          101      0  11110515  ...        -0.538462        -1.000000     -0.428571
4          101      0  11110515  ...        -0.341463        -0.538462     -0.597561
...        ...    ...       ...  ...              ...              ...           ...
1048570    103     22  11650531  ...        -0.526316        -0.346154     -0.513208
1048571    103     22  11650531  ...        -0.169231         0.276596     -0.299270
1048572    103     22  11650531  ...        -0.428571        -0.200000     -0.383929
1048573    103     22  11650531  ...        -0.125000         0.090909     -0.350000
1048574    103     22  11650531  ...         0.200000         0.565217     -0.400000

[1048575 rows x 33 columns]